### ISSUE TITLE
unable to create new project

### ISSUE THREAD

**Issue by xtreampb** [aws/lumberyard#360]
**Describe the bug**
Can't create new project

**Steps to reproduce**
install lumberyard 1.16.0
install all required plugins and SDKs
ignore optional SDKs
move install folder to separate disk
re-run setup assistant to validate paths
create new project using default template
recieve following error:
`"G:\Amazon\Lumberyard\1.16.0.0\dev\lmbr_waf.bat" build_win_x64_vs2017_profile --enabled-game-projects=Sandbox -p Sandbox
[WAF] Engine Root: G:\Amazon\Lumberyard\1.16.0.0\dev\
A custom BuildEnv.json file was not found. This build will be untagged.
A custom BuildEnv.json file was not found. This build will be untagged.
[WAF] Executing 'build_win_x64_vs2017_profile' in 'g:\Amazon\Lumberyard\1.16.0.0\dev\BinTemp\win_x64_vs2017_profile'
[WARN] Game folder 'StarterGame' configured in bootstrap.cfg is the enabled game for this build.  In order to run or debug for the game 'Sandbox', they need to be set in bootstrap.cfg under the 'sys_game_folder' entry accordingly
[WARNING] Incredibuild disabled by build option
[WARN] 3rd Party alias 'qt' specified in g:\Amazon\Lumberyard\1.16.0.0\dev\Code\Tools\Woodpecker\wscript:54 (build) is not enabled. Make sure that at least one of the following roles is enabled: []
[WARN] 3rd Party alias 'qt' specified in g:\Amazon\Lumberyard\1.16.0.0\dev\Code\Tools\Woodpecker\wscript:101 (build) is not enabled. Make sure that at least one of the following roles is enabled: []
unable to find QT
unable to find QT
Traceback (most recent call last):
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Scripting.py", line 226, in waf_entry_point
    run_commands()
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Scripting.py", line 342, in run_commands
    ctx = run_command(cmd_name)
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Scripting.py", line 319, in run_command
    ctx.execute()
  File ".\Tools\build\waf-1.7.13\lmbrwaflib\msvs.py", line 1949, in override_build_state
    old(ctx)
  File "g:\Amazon\Lumberyard\1.16.0.0\dev\wscript", line 469, in execute
    return execute_method(self)
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Scripting.py", line 696, in execute
    return execute_method(self)
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Build.py", line 254, in execute
    self.execute_build()
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Build.py", line 277, in execute_build
    self.compile()
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Build.py", line 370, in compile
    self.producer.start()
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Runner.py", line 307, in start
    self.refill_task_list()
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Runner.py", line 209, in refill_task_list
    self.add_outstanding_tasks(next(self.biter))
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Build.py", line 818, in get_build_iterator
    self.post_group()
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\Build.py", line 789, in post_group
    f()
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\build\waf-1.7.13\waflib\TaskGen.py", line 218, in post
    v()
  File "Tools\build\waf-1.7.13\lmbrwaflib\cry_utils.py", line 893, in add_compiler_dependency
    if os.path.isabs( self.env['CC'] ):
  File "G:\Amazon\Lumberyard\1.16.0.0\dev\Tools\Python\2.7.12\windows\lib\ntpath.py", line 59, in isabs
    return s != '' and s[:1] in '/\\'
TypeError: 'in <string>' requires string as left operand, not list
Process failed with return code: 1
`

**Expected behavior**
Please provide a concise description of what you expected to happen.

**Screenshots/Logs**
Please include any relevant screenshots and log files from your game project directory (e.g., C:\Amazon\lumberyard\1.15.0.0\dev\Cache\YOURPROJECT\pc\user\log). Note that you are posting to a public forum so please remove any sensitive information from your log files such as project name & path, IP address, credentials etc.

**Lumberyard version**
State the version of Lumberyard in which you discovered this bug (e.g., v1.14.0.1 or v1.15.0.0 etc.).
1.16.0.0

**[OPTIONAL] What is your role in game development?**
Are you a game designer, engineer, artist, producer, something else?

**[OPTIONAL] Tell us about your project or studio.**
Briefly tell us about your project or studio.

**Comment by AMZN-alexpete** [comment]
Hi @xtreampb, in Setup Assistant did you select the option to compile "game", "game and engine" and "editor and tools"?  I believe there may be a known issue where you cannot create a new project unless you select all those options because some default Gems (EMotionFX) require that you compile the editor version of the Gem as well.  Can you try selecting all the compile options, installing required SDKs and re-creating your project?  Sorry for the inconvenience!

**Comment by xtreampb** [comment]
I still get the same issue.  Here are pictures of my setup:

![summary](https://user-images.githubusercontent.com/1777628/50014572-561f4c80-ff92-11e8-9170-4fb49a23e2b6.PNG)
![gettingstarted](https://user-images.githubusercontent.com/1777628/50014573-561f4c80-ff92-11e8-9b13-6a1cc82db393.PNG)
![install software](https://user-images.githubusercontent.com/1777628/50014574-56b7e300-ff92-11e8-9fab-a0330d15866f.PNG)
![installed plugins](https://user-images.githubusercontent.com/1777628/50014575-56b7e300-ff92-11e8-8686-369b224b428a.PNG)
![optional sdks](https://user-images.githubusercontent.com/1777628/50014576-56b7e300-ff92-11e8-886e-fa98fb8fab95.PNG)
![required sdks](https://user-images.githubusercontent.com/1777628/50014577-56b7e300-ff92-11e8-9a0f-db35f1c192db.PNG)

**Comment by AMZN-alexpete** [comment]
@xtreampb , it looks like all your SDKs are installed correctly and you should have no issues compiling.  Do you still get the same error that includes this message? 

[WARN] 3rd Party alias 'qt' specified in g:\Amazon\Lumberyard\1.16.0.0\dev\Code\Tools\Woodpecker\wscript:54 (build) is not enabled. Make sure that at least one of the following roles is enabled: [] 

If you enabled the Editor it should now have Qt in your 3rdParty folder.  Can you try the following please.
1. Delete your temp folder G:\Amazon\Lumberyard\1.16.0.0\dev\BinTemp
2. Open a command window and navigate to G:\Amazon\Lumberyard\1.16.0.0\dev
3. Run lmbr_waf configure
4. Run lmbr_waf build_win_x64_vs2017_profile -p all

This should re-compile the current active project and will hopefully give some more information about what might be wrong with the environment.  If this compiles without errors then please try creating your project again.

**Comment by AMZN-alexpete** [comment]
@xtreampb, I'm closing this issue due to inactivity.  If you are still experiencing this problem with 1.17 please open a new issue.
